# Generated by Django 4.0.5 on 2022-06-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_endereco', models.CharField(max_length=100)),
                ('cliente_telefone', models.CharField(max_length=100)),
                ('cliente_email', models.CharField(max_length=100)),
                ('cliente_data_cadastro', models.DateField()),
                ('cliente_data_nascimento', models.DateField()),
                ('cliente_password', models.CharField(max_length=150)),
                ('cliente_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('produtos_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_preco', models.CharField(max_length=100)),
                ('produto_descricao', models.CharField(max_length=120)),
                ('produto_vendedor', models.CharField(max_length=100)),
                ('produto_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='encomenda',
            fields=[
                ('encomenda_id', models.AutoField(primary_key=True, serialize=False)),
                ('encomenda_data_cadastro', models.DateField()),
                ('encomenda_data_entrega', models.DateField()),
                ('encomenda_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendas.cliente')),
                ('encomenda_produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendas.produtos')),
            ],
        ),
    ]
